### ISSUE TITLE
Snowflake grant-all modules have conflicting shares and on_future

### ISSUE THREAD

**Issue by lundbird** [chanzuckerberg/cztack#282]
This is the issue brought up in this discussion topic: https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/318

@jhettler @ryanking

**Comment by curtisq** [comment]
Also running into this- would like to know what others have done as a workaround.

**Comment by TonyGaul** [comment]
Just wondering if we can apply some conditional logic to "shares"?

This might handle the following combinations.
on_future = true
shares        = []

on_future = true
shares        = null

on_future = true
# shares        = []


For example in snowflake-schema-grant-all

"shares": "${length(coalesce(var.shares, [])) == 0 ? null : setunion(\n\t\t\t\tvar.shares,\n\t\t\t\tlookup(var.per_privilege_grants, each.value, { shares = [], roles = [] }).shares,\n\t\t\t\t)}",

**Comment by nakazono1011** [comment]
I still have problems with this issue. Please provide me with a solution.
